version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: titanic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  backend:
    build: ./backend
    restart: always
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: postgres
      PGDATABASE: titanic
      PGPORT: 5432
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app


  frontend:
    build: .
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
