name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            daagerk/titanic-dashboard:latest
            daagerk/titanic-dashboard:v0.0.2
          

      # Optional: Tag with git commit SHA
      - name: Build and push with commit tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: daagerk/titanic-dashboard:${{ github.sha }}
